smiles-columns = [polymer_smiles, solvent_smiles]
descriptors-columns = [T_K, volume_fraction]
data-path = data/dataset-s1.csv
target-columns = [average_IP]
task-type = regression
metrics = [rmse, mae, r2]
epochs = 300
pytorch-seed = 7
num-workers = 0
batch-size = 128
accelerator = auto
devices = auto
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
ensemble-size = 1
message-hidden-dim = 900
depth = 4
dropout = 0.0
aggregation = norm
aggregation-norm = 138
activation = PRELU
ffn-hidden-dim = 1000
ffn-num-layers = 1
multiclass-num-classes = 3
atom-ffn-hidden-dim = 300
atom-ffn-num-layers = 1
atom-multiclass-num-classes = 3
bond-ffn-hidden-dim = 300
bond-ffn-num-layers = 1
bond-multiclass-num-classes = 3
atom-constrainer-ffn-hidden-dim = 300
atom-constrainer-ffn-num-layers = 1
bond-constrainer-ffn-hidden-dim = 300
bond-constrainer-ffn-num-layers = 1
v-kl = 0.0
eps = 1e-08
alpha = 0.1
tracking-metric = val_loss
warmup-epochs = 32
init-lr = 0.0019380201344492303
max-lr = 0.009575856418190825
final-lr = 0.0008958638171169953
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
splits-file = data/cv10-splits.json
num-replicates = 1
data-seed = 0
output-dir = dmpnn_best_300epochs
